# Generated by Django 5.2 on 2025-05-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vocation',
            old_name='end_date',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='vocation',
            old_name='start_date',
            new_name='start',
        ),
        migrations.AddField(
            model_name='vocation',
            name='file',
            field=models.FileField(default=1, upload_to='files/vocations'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accesscontrol',
            name='status',
            field=models.CharField(choices=[('arrived', 'Kelgan'), ('late', 'Kech qoldi'), ('failed', 'Failed'), ('in_vocation', "Ta'tilda")], max_length=20),
        ),
    ]
