# Generated by Django 5.2 on 2025-05-05 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_rename_end_date_vocation_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocation',
            name='type',
            field=models.CharField(default="Mehnat ta'tili", max_length=1000),
        ),
    ]
