# Generated by Django 5.2 on 2025-05-05 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_vocation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocation',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vocation',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
