# Generated by Django 5.2 on 2025-10-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_vocation_created_alter_vocation_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_accept',
            field=models.BooleanField(default=False),
        ),
    ]
