# Generated by Django 5.2 on 2026-04-20 06:06

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_is_accept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesscontrol',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='employee',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100),
        ),
    ]
